name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        gradle-version: '8.2'
        
    - name: Install NPM Dependencies (api)
      run: |
        cd api
        npm install
        
    - name: Install NPM Dependencies (frontend)
      run: |
        cd frontend
        npm install

    - name: Start API (with test environment)
      run: |
        cd api
        JWT_SECRET=f6d278bb34e1d0e146a80b16ec254c05 npm run start:test
        sleep 5

    - name: Start Frontend
      run: |
        cd frontend
        npm start
        sleep 5
        
    - name: Build and Run Selenium Tests
      run: |
          ./gradlew clean test
