name: Java CI with Gradle and NPM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        gradle-version: '8.2'

    - name: Install Node.js and NVM
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18

    - name: Install MongoDB
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org
        sudo systemctl start mongod
        sleep 10  # Wait for MongoDB to start

    - name: Install NPM Dependencies (api)
      run: |
        cd api
        npm install

    - name: Install NPM Dependencies (frontend)
      run: |
        cd frontend
        npm install

    - name: Start API (with test environment)
      run: |
        cd api
        echo "Starting API with test environment"
        JWT_SECRET=f6d278bb34e1d0e146a80b16ec254c05 MONGODB_URL='mongodb://localhost/acebook_test' npm run start:test &
        while ! curl -s http://localhost:3000/health-check; do sleep 5; done

    - name: Start Frontend
      run: |
        cd frontend
        npm start
        sleep 5

    - name: Build and Run Selenium Tests
      run: |
        ./gradlew clean test
